title: Tink's App
description: Tink's personal site.
theme: just-the-docs
favicon: /favicon.ico

url: https://tinks.app

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
